version: "3.9"
services:
  bot:
    platform: linux/arm64 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    env_file:
      - .env.local
    volumes:
      - ./:/pirate-listing-bot
      - ignore:/pirate-listing-bot/node_modules
volumes:
  ignore: